export const seed = async (knex) => {
  await knex('tasks').del();
  await knex('progress').del();
  
  const tasks = [
    // CAREER TASKS
    { task_key: 'career_1', domain: 'career', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Update LinkedIn profile with "DevSecOps Engineer" headline, professional photo, detailed experience section', detail: 'Use Canva (free) for headshot background cleanup. Write headline: "DevSecOps Engineer | Node.js | Kubernetes | AWS". Experience: quantify impact with numbers.', tags: 'free,30 mins,do today' },
    { task_key: 'career_2', domain: 'career', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Create Toptal profile and apply — pass screening, technical interview, test project', detail: 'Toptal.com — top 3% freelance network. $60-150/hr contracts. Rigorous vetting (English test, tech screening, live coding, test project). Prepare 2-3 weeks.', tags: '$60-150/hr,2-3 week process' },
    { task_key: 'career_3', domain: 'career', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Apply to Arc.dev, Contra, Gun.io — submit profiles to all 3 platforms this week', tags: 'vetted platforms,do this week' },
    { task_key: 'career_4', domain: 'career', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Raise freelance rate to $35-50/hr immediately on Upwork/Fiverr. Update all proposals.', tags: 'immediate action,highest ROI' },
    { task_key: 'career_5', domain: 'career', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Build portfolio site with Next.js — 3 best projects, case studies, contact form, deployed on Vercel', detail: 'Use Next.js 14 + Tailwind. Show: problem → solution → tech stack → results (metrics). Deploy free on Vercel. Domain: yourname.dev (~$12/year via Namecheap).', tags: 'free hosting,$12/year domain' },
    { task_key: 'career_6', domain: 'career', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Write 2 technical articles on Dev.to or Medium — NestJS auth, K8s deployment, or DevSecOps topic', tags: 'free,builds authority' },
    { task_key: 'career_7', domain: 'career', phase: 'M 4-6', quarter_tag: 'Y1-Q2', title: 'Complete AWS Solutions Architect Associate certification — study 6-8 weeks, pass exam', detail: 'Study: Stephane Maarek Udemy course (~$15), AWS free tier hands-on. Exam: $150 USD. Opens $80-120/hr contracts.', tags: '$165 total,6-8 weeks,high ROI' },
    { task_key: 'career_8', domain: 'career', phase: 'M 4-6', quarter_tag: 'Y1-Q2', title: 'Complete Certified Kubernetes Administrator (CKA) — study 8 weeks, pass exam', detail: 'Study: Mumshad Udemy course (~$15), practice on Killer.sh. Exam: $395. Unlocks $100-150/hr DevOps contracts.', tags: '$410 total,8 weeks' },
    { task_key: 'career_9', domain: 'career', phase: 'M 4-6', quarter_tag: 'Y1-Q2', title: 'Land first $50-80/hr contract on Toptal or Arc — 20+ hrs/week, 3+ month engagement', tags: 'target rate,stable contract' },
    { task_key: 'career_10', domain: 'career', phase: 'M 7-12', quarter_tag: 'Y1-Q3', title: 'Complete AWS Security Specialty OR DevOps Engineer Professional cert', tags: '$300,$100+/hr unlock' },
    { task_key: 'career_11', domain: 'career', phase: 'M 7-12', quarter_tag: 'Y1-Q3', title: 'Publish 10+ technical articles — build SEO presence, inbound leads', tags: 'free,long-term asset' },
    { task_key: 'career_12', domain: 'career', phase: 'M 7-12', quarter_tag: 'Y1-Q4', title: 'Speak at 1 local tech meetup (Nairobi JS, DevOps Kenya, iHub event)', tags: 'free,network unlock' },
    { task_key: 'career_13', domain: 'career', phase: 'M 7-12', quarter_tag: 'Y1-Q4', title: 'Achieve $80/hr+ rate on primary contract — renegotiate or switch client', tags: 'Year 1 target' },
    { task_key: 'career_14', domain: 'career', phase: 'Y 2-3', quarter_tag: 'Y2-Q1', title: 'Launch YouTube channel — "DevSecOps for African Developers" — 1 video/week for 12 weeks', tags: 'free,builds brand' },
    { task_key: 'career_15', domain: 'career', phase: 'Y 2-3', quarter_tag: 'Y2-Q2', title: 'Complete Offensive Security Certified Professional (OSCP) — 90 days lab + exam', detail: 'OSCP = gold standard penetration testing cert. $1,649 for 90-day lab access + exam attempt. Study: 3-4 months intense. Unlocks $120-180/hr security contracts.', tags: '$1,649,3-4 months,elite cert' },
    { task_key: 'career_16', domain: 'career', phase: 'Y 2-3', quarter_tag: 'Y2-Q3', title: 'Build and launch SaaS MVP — solve a $50-200/month problem for 10-50 customers', tags: 'Year 2-3,first product' },
    { task_key: 'career_17', domain: 'career', phase: 'Y 2-3', quarter_tag: 'Y2-Q4', title: 'Reach $100-120/hr consulting rate — senior DevSecOps specialist positioning', tags: 'Year 2 target' },
    { task_key: 'career_18', domain: 'career', phase: 'Y 4-5', quarter_tag: 'Y4-Q1', title: 'Register consultancy as Kenyan company — KRA PIN, business permit, company bank account', tags: 'KES 10-30k,Year 3-4' },
    { task_key: 'career_19', domain: 'career', phase: 'Y 4-5', quarter_tag: 'Y4-Q2', title: 'Hire first contract developer — delegate $30-50/hr work while you bill $100-150/hr', tags: 'leverage unlock' },
    { task_key: 'career_20', domain: 'career', phase: 'Y 4-5', quarter_tag: 'Y4-Q3', title: 'Land 2-3 retainer clients at $3,000-6,000/month each — DevSecOps consulting packages', tags: 'Year 4-5,recurring revenue' },
    { task_key: 'career_21', domain: 'career', phase: 'Y 4-5', quarter_tag: 'Y5-Q1', title: 'SaaS at $5k+ MRR OR consulting company at $10k+/month revenue', tags: '5-year milestone' },

    // HEALTH TASKS
    { task_key: 'health_1', domain: 'health', phase: 'M 1-2', quarter_tag: 'Y1-Q1', title: 'Book full body medical checkup within 7 days — blood work (CBC, glucose, lipids, thyroid, liver), blood pressure, BMI', detail: 'Nairobi: MP Shah, Nairobi Hospital, Aga Khan, or local clinic. Cost: KES 2,000–5,000. You cannot manage what you haven\'t measured.', tags: 'KES 2–5k,this week' },
    { task_key: 'health_2', domain: 'health', phase: 'M 1-2', quarter_tag: 'Y1-Q1', title: 'Record starting measurements: weight, waist, chest, hips. Photograph. Weigh every Monday morning before food.', tags: 'free,motivation data' },
    { task_key: 'health_3', domain: 'health', phase: 'M 1-2', quarter_tag: 'Y1-Q1', title: 'Set fixed sleep schedule: 10:30pm in bed, 6:00am wake. No screens 30 mins before bed. Phone charges outside bedroom.', tags: 'free,7.5 hrs target' },
    { task_key: 'health_4', domain: 'health', phase: 'M 1-2', quarter_tag: 'Y1-Q1', title: 'Install Sleep Cycle app (free) — track sleep quality for 14 days before making changes', tags: 'free app,data-first' },
    { task_key: 'health_5', domain: 'health', phase: 'M 1-2', quarter_tag: 'Y1-Q1', title: 'Walk briskly 30 minutes every morning for 6 weeks — 6:00–6:30am. Use Uhuru Park, Karura Forest, or your neighbourhood. Target 7,000 steps/day.', tags: 'free,daily,foundation habit' },
    { task_key: 'health_6', domain: 'health', phase: 'M 1-2', quarter_tag: 'Y1-Q1', title: 'Begin plate method portion control immediately: ½ plate vegetables, ¼ protein, ¼ carbs. Drink one full glass of water before every meal.', tags: 'free,immediate impact' },
    { task_key: 'health_7', domain: 'health', phase: 'M 3-6', quarter_tag: 'Y1-Q2', title: 'Join a gym and start StrongLifts 5×5 program (free app) — 3 days/week, compound movements: Squat, Deadlift, Bench, Row, Overhead Press', detail: 'Nairobi gyms: Gymkhana (~KES 2,500/month), Power World, Lifestyle Fitness. 45 mins/session. No isolation exercises until Month 6.', tags: 'KES 2–4k/month,3x/week' },
    { task_key: 'health_8', domain: 'health', phase: 'M 3-6', quarter_tag: 'Y1-Q2', title: 'Start Couch to 5K (C25K) app — free NHS version. Run/walk intervals 3x/week on gym off-days. Week 1: 60s run/90s walk × 8.', tags: 'free app,3x/week,9-week programme' },
    { task_key: 'health_9', domain: 'health', phase: 'M 3-6', quarter_tag: 'Y1-Q2', title: 'Track calories in MyFitnessPal for 30 days — create a 500 calorie/day deficit (= 0.5kg/week loss = ~24kg/year)', tags: 'free app,30-day sprint' },
    { task_key: 'health_10', domain: 'health', phase: 'M 3-6', quarter_tag: 'Y1-Q2', title: 'Increase daily protein to 1.6g per kg of target bodyweight — eggs (KES 12 each), tilapia, chicken, beans/maharagwe, lentils', tags: 'budget-friendly,most impactful diet change' },
    { task_key: 'health_11', domain: 'health', phase: 'M 3-6', quarter_tag: 'Y1-Q2', title: 'Register for Stanchart Nairobi Marathon 5K or 10K (October) — pay entry fee today. Entry: ~KES 1,500–3,000.', tags: 'KES 1,500–3,000,commitment device' },
    { task_key: 'health_12', domain: 'health', phase: 'M 7-12', quarter_tag: 'Y1-Q3', title: 'Complete C25K → Bridge to 10K. Running 10K non-stop by Month 9.', tags: 'free,8 more weeks after C25K' },
    { task_key: 'health_13', domain: 'health', phase: 'M 7-12', quarter_tag: 'Y1-Q3', title: 'Hit −15kg by Month 7 — celebrate publicly to reinforce identity shift. Monthly progress photos.', tags: 'identity reinforcement' },
    { task_key: 'health_14', domain: 'health', phase: 'M 7-12', quarter_tag: 'Y1-Q4', title: 'Run your first race. Cross the finish line. Bring a family member to the finish.', tags: 'life milestone,identity defining' },
    { task_key: 'health_15', domain: 'health', phase: 'M 7-12', quarter_tag: 'Y1-Q4', title: 'By Month 12: 4x exercise/week, 7.5 hrs sleep, 2L water daily, annual medical checkup booked. These run automatically.', tags: 'permanent system' },

    // FINANCE TASKS
    { task_key: 'finance_1', domain: 'finance', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Create your first zero-based budget this week — every shilling of income assigned before the month begins. Use Google Sheets (free).', detail: 'Categories: Tithe/Giving (10%), Savings (20%), Debt, Food, Transport, Airtime/Data, Clothing, Entertainment. Income − all expenses = KES 0.', tags: 'Google Sheets free,do this week' },
    { task_key: 'finance_2', domain: 'finance', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Open a separate M-Pesa or bank savings account labelled "EMERGENCY FUND" — target KES 50,000. Contribute every time income arrives.', tags: 'free,KES 50k target' },
    { task_key: 'finance_3', domain: 'finance', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Write down every debt: lender, amount owed, interest rate, minimum payment. Fuliza/M-Shwari/Tala charge 2–15%/month — these clear first.', tags: '30 mins,debt inventory' },
    { task_key: 'finance_4', domain: 'finance', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Debt Avalanche Method: pay minimums on all. Every extra shilling → highest interest debt first. Roll payment when debt cleared.', tags: 'mathematically optimal' },
    { task_key: 'finance_5', domain: 'finance', phase: 'M 1-3', quarter_tag: 'Y1-Q1', title: 'Raise freelance rate to $25–35/hr immediately on all platforms. One 10hr/week contract at $30/hr = $1,200/month (KES 155k). Do this today.', tags: 'highest ROI action,do today' },
    { task_key: 'finance_6', domain: 'finance', phase: 'M 4-12', quarter_tag: 'Y1-Q2', title: 'Join a Sacco (Unaitas, Stima, or employer Sacco) — contribute KES 2,000–5,000/month. 8–14% annual dividend. Loan access at 1%/month.', tags: 'KES 2–5k/month,8–14% returns' },
    { task_key: 'finance_7', domain: 'finance', phase: 'M 4-12', quarter_tag: 'Y1-Q3', title: 'Start investing in Kenya T-Bills via CBK DhowCSD (csd.cbk.go.ke) — free to register, minimum KES 50,000, ~16–18% annual return. Government-guaranteed.', tags: 'KES 50k minimum,~16–18% returns' },
    { task_key: 'finance_8', domain: 'finance', phase: 'M 4-12', quarter_tag: 'Y1-Q3', title: 'Start income stream #2: record a 3–5 hour "NestJS + TypeScript for Beginners" course. Publish on Udemy (free to publish, earn 37–97% royalty).', tags: 'free to start,passive income stream 2' },
    { task_key: 'finance_9', domain: 'finance', phase: 'M 4-12', quarter_tag: 'Y1-Q4', title: 'Start NSE investing via Hisa app (hisafrika.com) — KES 100 minimum. Dollar-cost average KES 5,000/month into Safaricom, Equity Group, or global ETFs.', tags: 'KES 100 minimum,long-term' },
    { task_key: 'finance_10', domain: 'finance', phase: 'Y 2-5', quarter_tag: 'Y2-Q1', title: 'Stream 1: Active freelance/contract income — $50–80/hr by Year 2 (primary engine)', tags: 'active income' },
    { task_key: 'finance_11', domain: 'finance', phase: 'Y 2-5', quarter_tag: 'Y2-Q2', title: 'Stream 2: Digital products — Udemy course + YouTube ad revenue. Target: KES 20–50k/month passive by Year 2.', tags: 'passive' },
    { task_key: 'finance_12', domain: 'finance', phase: 'Y 2-5', quarter_tag: 'Y3-Q1', title: 'Stream 3: Kenya T-Bills and Bonds via DhowCSD. Build to KES 500k by Year 3 = ~KES 80–90k annual passive income.', tags: 'passive,government guaranteed' },
    { task_key: 'finance_13', domain: 'finance', phase: 'Y 2-5', quarter_tag: 'Y3-Q2', title: 'Stream 4: NSE stocks via Hisa + Safaricom/Equity dividends. KES 5,000–10,000/month invested consistently.', tags: 'long-term' },
    { task_key: 'finance_14', domain: 'finance', phase: 'Y 2-5', quarter_tag: 'Y3-Q3', title: 'Stream 5: First plot of land by Year 3 — Kitengela/Ruiru/Juja. KES 400–800k per 1/8 acre. Use Sacco loan + savings. This is your generational asset.', tags: 'Year 3,generational wealth' },
    { task_key: 'finance_15', domain: 'finance', phase: 'Y 2-5', quarter_tag: 'Y3-Q4', title: 'Stream 6: Company equity — DevSecOps consultancy retainers. $3,000–6,000/month recurring by Year 3.', tags: 'Year 3,largest wealth vehicle' },
    { task_key: 'finance_16', domain: 'finance', phase: 'Y 2-5', quarter_tag: 'Y4-Q1', title: 'Stream 7: Music income — performances (KES 5–15k), lessons (KES 2–5k/hr), studio production. Year 3–5.', tags: 'Year 3–5,identity-income alignment' },

    // FAMILY TASKS
    { task_key: 'family_1', domain: 'family', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'Identify 2–3 trusted men — invite them to a monthly accountability meeting (in-person or WhatsApp voice call). Monthly agenda: commitments, struggles, goals.', tags: 'free,isolation antidote' },
    { task_key: 'family_2', domain: 'family', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'Install the 1-message interrupt rule: when you feel the urge to withdraw, send one text to your circle first — even "I\'m in a heavy week, pray for me."', tags: 'pattern interrupt' },
    { task_key: 'family_3', domain: 'family', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'Find 3 potential mentors (tech/business, faith/character, marriage/family) and reach out to one this month using the formula below.', tags: 'this month' },
    { task_key: 'family_4', domain: 'family', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'Write your "Partner Clarity Document" — non-negotiable values, family vision, personal red flags, what you bring, what you\'re working on. Private. 1–2 hrs.', tags: 'private document,sharpens discernment' },
    { task_key: 'family_5', domain: 'family', phase: 'Now', quarter_tag: 'Y1-Q2', title: 'Read "The 5 Love Languages" (Chapman) and "Boundaries" (Cloud & Townsend) — before marriage, not after. ~4–6 hrs each.', tags: '~$15 each,foundation reading' },
    { task_key: 'family_6', domain: 'family', phase: 'Now', quarter_tag: 'Y2-Q1', title: 'Financial readiness gate before marriage: debt-free, KES 200k savings, stable income KES 150k+/month. Track progress monthly.', tags: 'Year 2 target,financial readiness gate' },

    // FAITH TASKS
    { task_key: 'faith_1', domain: 'faith', phase: 'Month 1', quarter_tag: 'Y1-Q1', title: 'Set a 20-minute spiritual block at 6:00–6:20am before phone. Structure: 5 min thanksgiving/prayer, 10 min scripture, 5 min journalling. Daily, non-negotiable.', tags: '20 mins,before phone always' },
    { task_key: 'faith_2', domain: 'faith', phase: 'Month 1', quarter_tag: 'Y1-Q1', title: 'Install YouVersion Bible app (free) — enroll in "Bible in a Year" plan. 10–15 minutes per day. Track your streak. Complete entire Bible in 12 months.', tags: 'free,12-month commitment' },
    { task_key: 'faith_3', domain: 'faith', phase: 'Month 1', quarter_tag: 'Y1-Q1', title: 'Buy a physical journal — begin daily prayer and reflection entries. Date every entry. Write what you prayed and what you sense God saying. Even 3–5 sentences.', tags: 'KES 200–500,irreplaceable record' },
    { task_key: 'faith_4', domain: 'faith', phase: 'Month 1', quarter_tag: 'Y1-Q1', title: 'Begin monthly 24-hour fast (dinner to dinner) from Month 2 — use meal times for prayer. Track insights in journal. Fasting days produce the clearest direction.', tags: '1x/month,Month 2 start' },
    { task_key: 'faith_5', domain: 'faith', phase: 'Month 1', quarter_tag: 'Y1-Q1', title: 'Find a spiritual mentor within your church — approach pastor or respected elder. Ask for monthly 60-min prayer and spiritual direction meeting.', tags: 'monthly,calling accelerator' },
    { task_key: 'faith_6', domain: 'faith', phase: 'Month 1', quarter_tag: 'Y1-Q2', title: 'Read Year 1 books: "The Purpose Driven Life" (Warren) · "Spiritual Disciplines for the Christian Life" (Whitney) · "Knowing God" (Packer) — one per quarter', tags: '~$15 each,one per quarter' },

    // MUSIC TASKS
    { task_key: 'music_1', domain: 'music', phase: 'M 1-6', quarter_tag: 'Y1-Q1', title: 'Design 45-min daily bass practice: 10 min scales/warmup, 15 min technique (alternating fingers, muting, pocket playing with metronome), 20 min songs', tags: '45 mins/day,structured beats random' },
    { task_key: 'music_2', domain: 'music', phase: 'M 1-6', quarter_tag: 'Y1-Q1', title: 'Study BassBuzz YouTube channel (Josh Fossgreen) — free, structured beginner-to-intermediate lessons. Then upgrade to Scott\'s Bass Lessons when ready.', tags: 'free on YouTube,SBL ~$179/year later' },
    { task_key: 'music_3', domain: 'music', phase: 'M 1-6', quarter_tag: 'Y1-Q2', title: 'Learn music theory on bass: major scale (all positions), pentatonic minor, chord tones (root/3rd/5th/7th), modes. Use "Music Theory for Bass Players" by Ariane Cap.', tags: '~$25 book,apply immediately' },
    { task_key: 'music_4', domain: 'music', phase: 'M 1-6', quarter_tag: 'Y1-Q2', title: 'Increase church worship team bass role — play regularly with a band. This accelerates skill 3–4x faster than solo practice. Ask for a regular weekly slot.', tags: 'free,fastest growth path' },
    { task_key: 'music_5', domain: 'music', phase: 'M 1-6', quarter_tag: 'Y1-Q2', title: 'Record yourself playing every week — video on phone. Review with one question: "What is the single thing I\'d fix?" Fix that one thing next week.', tags: 'free,most honest feedback' },
    { task_key: 'music_6', domain: 'music', phase: 'Y 2-3', quarter_tag: 'Y2-Q1', title: 'Build starter studio for KES 50–80k: Focusrite Scarlett Solo (~KES 12k), AT2020 mic (~KES 10k), Sony MDR-7506 headphones (~KES 12k), Reaper DAW (~KES 3k), acoustic foam (~KES 8k)', detail: 'Source from Moi Avenue music stores, Nairobi or Jumia. Reaper is the best value DAW. Logic Pro X (~KES 6k) if you use Mac.', tags: 'KES 50–80k total,Year 2' },
    { task_key: 'music_7', domain: 'music', phase: 'Y 2-3', quarter_tag: 'Y2-Q2', title: 'Learn music production: Produce Like A Pro YouTube (free, 50+ hrs). Produce one complete track from scratch by end of Year 2 — bass, drums, melody, basic mix.', tags: 'free,production portfolio piece' },
    { task_key: 'music_8', domain: 'music', phase: 'Y 2-3', quarter_tag: 'Y2-Q3', title: 'Offer bass guitar lessons to 2–3 students at KES 2,000–3,000/session. 3 students × 4 sessions/month = KES 24,000/month (income stream 7).', tags: 'KES 24k/month potential,Year 2' },

    // COMMUNITY TASKS
    { task_key: 'community_1', domain: 'community', phase: 'Now → Y2', quarter_tag: 'Y1-Q1', title: 'Choose 2 people you currently advise — invite them into a structured monthly mentorship (monthly 90-min meeting, prepared content, tracked progress)', tags: '2 mentees,monthly 90 mins' },
    { task_key: 'community_2', domain: 'community', phase: 'Now → Y2', quarter_tag: 'Y1-Q2', title: 'Create a free "Getting Into Tech in Kenya" PDF/Notion guide — what to learn, free resources, how to get a first remote job. Share via WhatsApp and church.', tags: 'free to create,multiplies impact' },
    { task_key: 'community_3', domain: 'community', phase: 'Now → Y2', quarter_tag: 'Y1-Q3', title: 'Run quarterly free 2-hr tech workshops at church/community hall for 15–20 youth. Topics: "Build Your First Website," "How to Get a Remote Job as a Kenyan Dev."', tags: '4x/year,builds pipeline' },
    { task_key: 'community_4', domain: 'community', phase: 'Now → Y2', quarter_tag: 'Y2-Q1', title: 'Partner with church/NGO to run a 4-week "Intro to Tech" Saturday programme for 16–25yr olds (Week 1: career paths, Week 2: HTML/CSS, Week 3: JS, Week 4: job search)', tags: 'Year 2,bootcamp prototype' },
    { task_key: 'community_5', domain: 'community', phase: 'Now → Y2', quarter_tag: 'Y4-Q1', title: 'Register a CBO or NGO for your tech bootcamp (KES 4,000–10,000 via Social Services). Name it. Give it a mission statement. Enables grants and corporate partnerships.', tags: 'KES 4–10k,Year 4' },
    { task_key: 'community_6', domain: 'community', phase: 'Now → Y2', quarter_tag: 'Y5-Q1', title: 'Launch 3-month intensive bootcamp (Year 5): 20 students, KES 15,000–30,000 fee, 50% scholarships subsidised by your company. Partner with Google/Microsoft for sponsorship.', tags: 'Year 5,20 students,legacy work' },

    // HABITS TASKS
    { task_key: 'habits_1', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '5:30am: Wake up. Alarm set. Phone face-down. Stand up immediately. Drink the glass of water placed on your bedside table the night before.', tags: 'alarm at 5:30am,start tomorrow' },
    { task_key: 'habits_2', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '5:30–5:50am: Spiritual block — 20 minutes of prayer, scripture (YouVersion app), and 3–5 lines of journalling. Phone only for Bible app. No social media, no WhatsApp.', tags: '20 mins,phone = Bible app only' },
    { task_key: 'habits_3', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '5:50–6:15am: Exercise — brisk walk around your neighbourhood (Months 1–2) OR gym session 3x/week (Month 3+). 25 minutes is enough.', tags: '25 mins walk / 45 mins gym,gym days: wake 5:15am' },
    { task_key: 'habits_4', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '6:15–6:30am: Shower + eat breakfast prepped the night before (3 boiled eggs, oats with fruit, or leftovers). Pack bag. Leave at 6:30am sharp.', tags: 'prep night before,zero decisions' },
    { task_key: 'habits_5', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: 'Set up your "Commute Learning Playlist" — assign each weekday a specific learning category so you never decide what to study on the matatu', tags: 'no decisions on the matatu,~5 hrs/week learning' },
    { task_key: 'habits_6', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: 'Download all content for offline use the night before — Spotify, YouTube Premium offline, Udemy offline. Nairobi matatu data can be unreliable.', tags: 'offline = no excuses,prep night before' },
    { task_key: 'habits_7', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '8:00am: Arrive at office. First 10 minutes: write your 3 office tasks for the day in Notion. No social media. No personal WhatsApp. Work starts at 8:00am sharp.', tags: '3 work priorities,no drift' },
    { task_key: 'habits_8', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: 'Lunch break (1:00–2:00pm): Eat first (20 mins). Then use 30–40 mins for: career reading (saved articles), replying to professional LinkedIn messages, or a short walk outside.', tags: 'walk + read,no social media' },
    { task_key: 'habits_9', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '5:00pm: Leave office on time. Use the end-of-day 5 minutes to write your ONE most important task for tomorrow on a sticky note — place it where you\'ll see it first thing.', tags: '5-min close,sets up tomorrow' },
    { task_key: 'habits_10', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: 'Evening commute learning schedule — different from morning to keep engagement high and cover more ground', tags: '~5 hrs/week second learning block,total: ~10 hrs/week on commute' },
    { task_key: 'habits_11', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '6:00–6:20pm: Transition ritual — change clothes, 5 mins of silence or prayer to decompress, drink water. Do not open laptop immediately. Let the commute energy settle.', tags: 'decompression ritual,do not skip' },
    { task_key: 'habits_12', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '6:20–7:05pm: Deep work on career side projects — TypeScript exercises, portfolio project, writing a technical article, or studying for a certification. 45 minutes, laptop open, phone away.', tags: '45 mins,career roadmap work,most important block' },
    { task_key: 'habits_13', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '7:05–7:50pm: Bass guitar practice — 45 minutes structured session (10 min scales, 15 min technique, 20 min songs). Use your instrument, not YouTube.', tags: '45 mins,instrument in hand' },
    { task_key: 'habits_14', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '7:50–8:30pm: Dinner with family. Phone away. Present. This is family time — not scroll time. Eat, talk, rest.', tags: 'family time,phone away' },
    { task_key: 'habits_15', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '8:30–9:30pm: Flexible evening block — financial tracking (budget check, 10 mins), reading (Atomic Habits, DDIA, or devotional book), OR extra career study if a deadline is close.', tags: 'flexible,wind down starts here' },
    { task_key: 'habits_16', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '9:30–10:00pm: Night routine — prep for tomorrow: download commute content, pack bag, boil eggs, lay out clothes, write sticky note for morning\'s ONE task, update Notion habit tracker.', tags: '30 mins,tomorrow\'s morning is built tonight' },
    { task_key: 'habits_17', domain: 'habits', phase: 'Week 1', quarter_tag: 'Y1-Q1', title: '10:00pm: Screens off. Phone on Do Not Disturb. In bed by 10:00–10:15pm. Sleep alarm set for 5:30am (gym days: 5:15am). Target: 7.5 hours sleep.', tags: '10:00pm hard cutoff,7.5 hrs target' },
    { task_key: 'habits_18', domain: 'habits', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'FIX 1 — Phone addiction: Delete Instagram, TikTok, Twitter/X from phone. Desktop-only, max 2x/day (12pm + 6pm, 20 mins each). Use Screen Time/Digital Wellbeing to enforce.', tags: 'delete apps today,remove the trigger' },
    { task_key: 'habits_19', domain: 'habits', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'FIX 2 — No workday boundaries: Set "Start Work" alarm at 8:00am and "Stop Work" alarm at 7:00pm. No work messages after 7pm. Parkinson\'s Law: the boundary creates urgency.', tags: 'two alarms' },
    { task_key: 'habits_20', domain: 'habits', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'FIX 3 — Procrastination: "Eat the Frog" (hardest task first, before email). "2-Minute Rule" (anything under 2 minutes: do immediately). Starting is the barrier, not the work.', tags: 'frog first every day' },
    { task_key: 'habits_21', domain: 'habits', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'FIX 4 — Not finishing: Weekly 3 system — identify only 3 priority outcomes per week every Sunday evening. Nothing else counts until those 3 are done.', tags: '3 priorities max,Sunday planning' },
    { task_key: 'habits_22', domain: 'habits', phase: 'Now', quarter_tag: 'Y1-Q1', title: 'FIX 5 — Saying yes too much: 24-hour rule — never commit immediately. Always say "Let me check my schedule and come back to you." Practice the phrase until automatic.', tags: '24-hour rule' },
    { task_key: 'habits_23', domain: 'habits', phase: 'This Week', quarter_tag: 'Y1-Q1', title: 'Set up free Notion workspace: Daily Habit Tracker (prayer, exercise, water, budget check, bass practice, reading), Weekly 3 Priorities, Monthly Goals per domain, Quarterly Review', tags: 'free,notion.so,build this week' },
    { task_key: 'habits_24', domain: 'habits', phase: 'This Week', quarter_tag: 'Y1-Q1', title: 'Sunday Weekly Review — 30 minutes every Sunday 8:00–8:30pm. Review past week (completed 3 priorities? habits streak?). Plan next week\'s 3 priorities. Highest-ROI weekly habit.', tags: '30 mins,Sunday ritual' },
    { task_key: 'habits_25', domain: 'habits', phase: 'This Week', quarter_tag: 'Y1-Q1', title: 'Monthly Review (last day of month): Review all 8 domains. What moved? What stalled? What needs to change next month? 60 minutes.', tags: '60 mins,monthly' },
    { task_key: 'habits_26', domain: 'habits', phase: 'This Week', quarter_tag: 'Y1-Q1', title: 'Read "Atomic Habits" by James Clear — implement 4 laws: Make it obvious, Make it attractive, Make it easy, Make it satisfying. Read in one week.', tags: '~$15,applies to everything' },

    // RISK TASKS
    { task_key: 'risk_1', domain: 'risk', phase: 'Actions', quarter_tag: 'Y1-Q1', title: 'Register for NHIF (National Hospital Insurance Fund) and a supplementary private health insurance plan (AAR, Jubilee, or Britam)', tags: 'KES 500–2,000/month,non-negotiable' },
    { task_key: 'risk_2', domain: 'risk', phase: 'Actions', quarter_tag: 'Y1-Q1', title: 'Open a Wise account (wise.com) — hold USD savings as partial hedge against KES volatility. Receive foreign client payments directly.', tags: 'free to open,USD hedge' },
    { task_key: 'risk_3', domain: 'risk', phase: 'Actions', quarter_tag: 'Y3-Q1', title: 'Write a simple will once you have assets (land, investments, company shares) — a local lawyer can draft this for KES 5,000–15,000', tags: 'KES 5–15k,Year 3+' },
    { task_key: 'risk_4', domain: 'risk', phase: 'Actions', quarter_tag: 'Y1-Q2', title: 'Keep a 3-month income-equivalent in T-Bills or Sacco as a liquid emergency reserve — never dip below this threshold', tags: 'permanent rule' },

    // RELATIONSHIPS TASKS
    { task_key: 'relationships_1', domain: 'relationships', phase: 'Actions', quarter_tag: 'Y1-Q1', title: 'Identify and reach out to 3 potential mentors this month — one in each category (tech, faith, marriage). Use the prepared outreach formula.', tags: 'this month' },
    { task_key: 'relationships_2', domain: 'relationships', phase: 'Actions', quarter_tag: 'Y1-Q1', title: 'Formalise brotherhood: invite 2–3 men to monthly accountability. Set a recurring calendar invite. Prepare a simple agenda template.', tags: 'monthly recurring' },
    { task_key: 'relationships_3', domain: 'relationships', phase: 'Actions', quarter_tag: 'Y1-Q1', title: 'Join at least 2 professional communities: iHub Nairobi events, KenyaDevs WhatsApp/Slack, or an online DevSecOps community. Show up consistently.', tags: 'professional network' },
    { task_key: 'relationships_4', domain: 'relationships', phase: 'Actions', quarter_tag: 'Y1-Q4', title: 'Annual relationship audit (December): List your top 10 relationships. Are they multiplying you? Are you investing in them? Any new ones needed? Any to limit?', tags: 'December annually' }
  ];

  await knex('tasks').insert(tasks);

  const domains = ['career', 'health', 'finance', 'family', 'faith', 'music', 'community', 'habits', 'risk', 'relationships'];
  const progressRecords = domains.map(domain => {
    const domainTasks = tasks.filter(t => t.domain === domain);
    return {
      domain,
      done_count: 0,
      total_count: domainTasks.length,
      percentage: 0
    };
  });

  await knex('progress').insert(progressRecords);
};

export default { seed };
